import fs from 'fs-extra';
import path from 'node:path';
import chalk from 'chalk';

// Any file we write contains "Riperflow" near the top (template headers,
// "Generated by Riperflow", etc.). If a file exists at the target path
// without this marker, it's a user-authored file we must not silently
// destroy — back it up first.
const RIPERFLOW_MARKER = /Riperflow/;

/**
 * Write `content` to `filePath`. If a pre-existing file at that path looks
 * user-authored (no Riperflow marker), move it to `<filePath>.bak-<ISO>`
 * before overwriting and log a one-line notice. Returns the backup path
 * when one was created, otherwise null.
 *
 * Closes Bug 19: prior code (`fs.outputFile`) silently clobbered any
 * existing CLAUDE.md / AGENT.md / CONVENTIONS.md without warning.
 */
export async function safeWrite(filePath: string, content: string): Promise<string | null> {
  let backupPath: string | null = null;

  if (await fs.pathExists(filePath)) {
    const existing = await fs.readFile(filePath, 'utf-8');
    if (!RIPERFLOW_MARKER.test(existing)) {
      const stamp = new Date().toISOString().replace(/[:.]/g, '-');
      backupPath = `${filePath}.bak-${stamp}`;
      await fs.move(filePath, backupPath);
      console.log(chalk.yellow(`  📦 Saved existing ${path.basename(filePath)} → ${path.basename(backupPath)}`));
    }
  }

  await fs.outputFile(filePath, content, 'utf-8');
  return backupPath;
}
